# Generated by Django 2.1.2 on 2018-11-03 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='year_of_disband',
            field=models.IntegerField(default=None),
        ),
    ]
