# Generated by Django 2.1.2 on 2018-11-06 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20181104_0748'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='src',
            field=models.CharField(default='media', max_length=100),
            preserve_default=False,
        ),
    ]
